categories: Categories
search: 搜索
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: 上一篇
older: 下一篇
share: 分享
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag